config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :admins
  namespace :admin do
    resources :contacts, only: [:create, :index, :show]
    resources :comunities, only: [:show, :index, :destroy]
    resources :comments, only: [:destroy]
    resources :posts, only: [:destroy]
    resources :bars, only: [:edit, :update, :destroy, :index, :show]
    resources :users, only: [:edit, :update, :index, :destroy]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    get 'bars/search' => 'bars#search', as: 'search'
    resources :bars, only: [:index, :create, :new, :show] do
        resources :favorites, only: [:index, :create, :destroy]
    end
    get 'users/:id/exit' => 'users#exit', as: 'exit'
    root to: 'top#index'
    resources :posts, only: [:destroy,:index, :update]
    get 'posts/:id/new' => 'posts#new', as: 'new_post'
    post 'posts/:id' => 'posts#create', as: 'create_post'
    resources :comments, only: [:create, :destroy]
    resources :comunities, only: [:create, :update, :destroy, :new, :show, :index]
    resources :contacts, only: [:create, :new]
    resources :notifications, only: [:index]
    resources :relationships, only: [:index, :create, :destroy]
    resources :users, only: [:edit, :update, :show]
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show]
    get '/about' => 'top#about', as: 'top_about'
    get 'bars/index/result' => 'bars#index_result', as: 'index_result'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :post
	belongs_to :user
	has_many :notifications, dependent: :destroy
	validates :body, presence: true
	acts_as_paranoid

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		Comment.create(comment_params)
		@comment = Comment.create(body: comment_params[:body], user_id: current_user.id)
		@comment.post = Post.find(params[:comment][:post_id])
		@post_id = params[:comment][:post_id]
		@post = @comment.post
		if @comment.save
			@post.create_notification_comment(current_user, @comment.id)
			render :index
		else
			render bar_path(params[:comment][:bar_id])
 		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@post_id = @comment.post_id
    	@comment.destroy
    	render :index
    	# redirect_to bar_path(params[:comment][:bar_id])
	end


	private
	def comment_params
		params.require(:comment).permit(:user_id,:post_id,:body)
  	end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div>コメントを投稿する</div>
	<%= form_with(model: [comment], url: comments_path(params[:id])) do |f| %>
	    <%= f.hidden_field :post_id,value:post.id %>
		<%= f.text_field :body, class: "col s9 form-control form-control-lg w-100 comment-body" %>
	<%= f.submit "投稿", class:" btn btn-small" %>
<% end %>

app/views/comments/_index.html.erb
<% if comments.any? %>
	<% comments.each do |comment| %>
		<div class="col s11 bar-show-box-comment-index">
			<div class="row"style="margin-bottom: 0;">
				<div class="col s4 ">
					<u>投稿者</u>：
                  	<%= link_to(user_path(comment.user)) do %>
                    	<span><%= comment.user.name %></span>
                  	<% end %>
		    	</div>
		    	<div class="col s4 bar-show-comment-date">
		        	<storng><%= comment.created_at.strftime("%m月%d日 %H時%M分") %></strong><br>
		    	</div>
		    	<% if user_signed_in? && comment.user == current_user %>
	        		<div class="bar-show-comment-delete"><%= link_to '削除', comment_path(comment), method: :delete,remote: true,"data-confirm" => "本当に消去しますか？",class:"col s2  offset-s1 #b71c1c red darken-4 bar-show-comment-delete" %>
		        	</div>
	      		<% end %>
	      	</div>
	      	<div class="row comment-body" style="margin-bottom: 0;">
	      		&emsp;&emsp;&emsp;&emsp;<b><%= comment.body %></b>
	   		</div>
	   	</div>
	<% end %>
<% else %>
	<div class="col s11 bar-show-box-comment-none">
		<div><b>まだコメントはありません</b></div>
	</div>
<% end %>

app/views/comments/index.js.erb
// console.log($("#post-<%= @post_id %>.comment_area"))
$("#post-<%= @post_id %>-comment_area").html("<%= j(render 'index', { comments: @comment.post.comments}) %>")
$(".comment-body").val('')