config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :admins
  namespace :admin do
    resources :contacts, only: [:create, :index, :show]
    resources :comunities, only: [:show, :index, :destroy]
    resources :comments, only: [:destroy]
    resources :posts, only: [:destroy]
    resources :bars, only: [:edit, :update, :destroy, :index, :show]
    resources :users, only: [:edit, :update, :index, :destroy]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    get 'bars/search' => 'bars#search', as: 'search'
    resources :bars, only: [:index, :create, :new, :show] do
        resources :favorites, only: [:index, :create, :destroy]
    end
    get 'users/:id/exit' => 'users#exit', as: 'exit'
    root to: 'top#index'
    resources :posts, only: [:destroy,:index, :update]
    get 'posts/:id/new' => 'posts#new', as: 'new_post'
    post 'posts/:id' => 'posts#create', as: 'create_post'
    resources :comments, only: [:create, :destroy]
    resources :comunities, only: [:create, :update, :destroy, :new, :show, :index]
    resources :contacts, only: [:create, :new]
    resources :notifications, only: [:index]
    resources :relationships, only: [:index, :create, :destroy]
    resources :users, only: [:edit, :update, :show]
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show]
    get '/about' => 'top#about', as: 'top_about'
    get 'bars/index/result' => 'bars#index_result', as: 'index_result'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/_admin_menu.html.erb
<div class="container">
	<div class="row">
		<div class="col s3 offset-s1">
			<div class="admin-user-index waves-effect waves-light btn-large #e0e0e0 grey lighten-2">
				<%= link_to "ユーザー一覧", admin_users_path %>
			</div>
		</div>
		<div class="col s3 offset-s1">
			<div class="admin-user-index waves-effect waves-light btn-large #e0e0e0 grey lighten-2">
				<%= link_to "登録店一覧", admin_bars_path %>
			</div>
		</div>
		<div class="col s3 offset-s1">
			<div class="admin-user-index waves-effect waves-light btn-large #e0e0e0 grey lighten-2">
				<%= link_to "お問い合わせ一覧", admin_contacts_path %>
			</div>
		</div>
	</div>
</div>