config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :admins
  namespace :admin do
    resources :contacts, only: [:create, :index, :show]
    resources :comunities, only: [:show, :index, :destroy]
    resources :comments, only: [:destroy]
    resources :posts, only: [:destroy]
    resources :bars, only: [:edit, :update, :destroy, :index, :show]
    resources :users, only: [:edit, :update, :index, :destroy]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    get 'bars/search' => 'bars#search', as: 'search'
    resources :bars, only: [:index, :create, :new, :show] do
        resources :favorites, only: [:index, :create, :destroy]
    end
    get 'users/:id/exit' => 'users#exit', as: 'exit'
    root to: 'top#index'
    resources :posts, only: [:destroy,:index, :update]
    get 'posts/:id/new' => 'posts#new', as: 'new_post'
    post 'posts/:id' => 'posts#create', as: 'create_post'
    resources :comments, only: [:create, :destroy]
    resources :comunities, only: [:create, :update, :destroy, :new, :show, :index]
    resources :contacts, only: [:create, :new]
    resources :notifications, only: [:index]
    resources :relationships, only: [:index, :create, :destroy]
    resources :users, only: [:edit, :update, :show]
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show]
    get '/about' => 'top#about', as: 'top_about'
    get 'bars/index/result' => 'bars#index_result', as: 'index_result'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bar.rb
class Bar < ApplicationRecord

	has_many :favorites, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user

	validates :name, presence: true
	validates :address, presence: true
	validates :category, presence: true
	validates :sports, presence: true

	attachment :image

	geocoded_by :address
	after_validation :geocode

	def favorited_by?(user)
    self.favorites.where(user_id: user.id).exists?
  end
  scope :score, -> { Bar.joins(:posts).where('posts.score >= 0.6').group('bars.id').order('count(posts.bar_id) DESC') }
end

app/controllers/admin/bars_controller.rb
class Admin::BarsController < ApplicationController
  def show
  	if admin_signed_in?
    	@bar = Bar.find(params[:id])
    	@posts = Post.where(bar_id: @bar.id).page(params[:page]).per(3)
    	@comment = Comment.new
    	@comments = Comment.where(post_id: @post_id).page(params[:page]).per(3)
    else
    	redirect_to root_path
    end
  end

  def index
  	if admin_signed_in?
    	@search = Bar.ransack(params[:q])
    	@bar_result = @search.result.page(params[:page]).per(10)
    else
    	redirect_to root_path
    end
  end

  def edit
  	if admin_signed_in?
  		@bar = Bar.find(params[:id])
  	else
  		redirect_to root_path
  	end
  end

  def update
  	@bar = Bar.find(params[:id])
  	if @bar.update(bar_params)
  		redirect_to admin_bar_path(@bar)
  	else
  		render :edit
  	end
  end

  def destroy
  	@bar = Bar.find(params[:id])
  	@bar.destroy
  	redirect_to admin_bars_path
  end

  private
  def bar_params
    params.require(:bar).permit(:name,:sports,:category,:image,:address,:body,:latitude,:longitude)
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def show
    @bar = Bar.find(params[:id])
    @favorite = Favorite.new
    @posts = Post.where(bar_id: @bar.id).page(params[:page]).per(3)
    @comment = Comment.new
    @comments = Comment.where(post_id: @post_id).page(params[:page]).per(3)
  end

  def new
    @bar = Bar.new
  end

  def create
    @bar = Bar.new(bar_params)
    if @bar.save
      redirect_to bars_path
    else
      render 'new'
    end
  end

  def search
    @bar = Bar.all
  end

  def index
    @search = Bar.ransack(params[:q])
    @bar_result = @search.result.page(params[:page]).per(10)
    @all_ranks = Bar.score.limit(3)
  end

  def index_result
    @search = Bar.ransack(params[:q])
    @bar_result = @search.result.page(params[:page]).per(10)
  end


  private
  def bar_params
    params.require(:bar).permit(:name,:sports,:category,:image,:address,:body,:latitude,:longitude)
  end
end

app/helpers/admin/bars_helper.rb
module Admin::BarsHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/views/admin/bars/edit.html.erb
<%= render 'admin/admin_menu' %>
<div class="container">
  <div class="row">
    <div class="col s3">
      <h5 class="admin-user-title"><%= @bar.name %></h5>
      <div class="border"></div>
    </div>
  </div>
  <div class="row">
    <div class="col s8 offset-s2 bar-new-box">
    	<%= form_for(@bar,url: admin_bar_path(@bar)) do |f| %>
      	<div class="col s4 offset-s4 bar-new-image">
    			<%= attachment_image_tag @bar, :image, :fill, 300, 300, format: 'jpg', fallback: "bar_no_image.png" %>
        	<%= f.attachment_field :image %>
    		</div>
        <div class="bar-new-name col s4 offset-s4">
       		<%= f.label :店名, class: "float-left" %><br>
					<%= f.text_field :name, class: "col-auto form-control form-control-lg w-100" %>
				</div>
				<div class="col s4 offset-s4">
    			<%= f.label :ジャンル, class: "float-left" %><br>
					<%= f.text_field :category, class: "col-auto form-control form-control-lg w-100" %>
				</div>
				<div class="col s4 offset-s4">
  				<%= f.label :住所, class: "float-left" %><br>
					<%= f.text_field :address, class: "col-auto form-control form-control-lg w-100" %>
				</div>
				<div class="col s4 offset-s4">
    			<%= f.label :普段観戦しているスポーツ, class: "float-left" %><br>
					<%= f.text_field :sports, class: "col-auto form-control form-control-lg w-100" %>
				</div>
				<div class="col s4 offset-s4">
    			<%= f.label :お店の紹介文, class: "float-left" %><br>
					<%= f.text_area :body, class: "col-auto form-control form-control-lg w-100" %>
				</div>
				<div class="bar-new-registration col s4 offset-s5">
					<%= f.submit "更新する", class:"col-xs-4 col-xs-offset-4 btn btn-primary" %>
				</div>
			<% end %>
   	</div>
  </div>
</div>

app/views/admin/bars/index.html.erb
<%= render 'admin/admin_menu' %>
<div class="container">
	<div class="row">
       	<div class="col s3">
       		<h5 class="admin-user-title">お店一覧</h5>
       		<div class="border"></div>
       	</div>
   	</div>
	<div class="row">
      	<%= search_form_for @search, url: admin_bars_path do |f| %>
	  		<%= f.search_field :name_or_sports_or_address_cont, class:"col s4 offset-s4", placeholder: '店名・住所・スポーツ名のいずれかを入力' %>
			<%= f.submit ' 検索する', class: "btn btn-primary" %>
	 	<% end %>
	</div>
   	<div class="row">
		<div class="col s12 bar-index-box-post-none">
    		<% if @bar_result.any? %>
				<table class="highlight">
			 		<thead class="thead-light">
						<tr>
							<th>写真</th>
			 				<th>店名</th>
				 			<th>ジャンル</th>
				 			<th>住所</th>
							<th>最終更新日</th>
							<th></th>
			 			</tr>
					</thead>
			 		<% @bar_result.each do |bar| %>
			 			<tbody>
							<tr>
		 						<td><%= attachment_image_tag bar, :image, :fill, 90, 90, format: 'jpg', fallback: "bar_no_image.png" %></td>
			 					<td><%= link_to(admin_bar_path(bar)) do %>
										<div><%= bar.name %></div>
									<% end %>
								</td>
				 				<td><%= bar.category %></td>
			 					<td><%= bar.address %></td>
			 					<td><%= bar.updated_at.strftime("%Y年%m月%d日 %H時%M分") %></td>
			 					<td><div><%= link_to "削除する" ,admin_bar_path(bar), method: :delete,"data-confirm" => "本当に消しますか？", class: "btn btn-success mx-auto btn-small #b71c1c red darken-4" %></div></td>
				 			</tr>
					<% end %>
		 				</tbody>
		 		</table>
			<% else %>
		 		<h6>お店が見つかりません。キーワードを変えてください。</h6>
		 	<% end %>
   		</div>
	</div>
	<div class="col s6 offset-s3 page-change">
        <%= paginate @bar_result, class: "paginate ,#546e7a blue-grey darken-1" %>
    </div>
   	<div class="post-index-blank" ></div>
</div>

app/views/admin/bars/show.html.erb
<%= render 'admin/admin_menu' %>
<div class="container">
  <div class="row">
    <div class="col s3">
      <h5 class="admin-user-title"><%= @bar.name %></h5>
      <div class="border"></div>
    </div>
    <div class="col s4 bar-show-post-new">
      <%= link_to "編集する", edit_admin_bar_path(@bar), class: "btn btn-success mx-auto btsn-lg" %>
    </div>
    <div class="col s3 offset-s3">
      <div class="admin-post-title">投稿一覧</div>
    </div>
  </div>
  <div class="row">
    <div class="col s5 bar-show-box">
      <div class="bar-show-image">
      	<%= attachment_image_tag @bar, :image, :fill, 200, 200, format: 'jpg', fallback: "bar_no_image.png",size:'200x200' %>
   		</div>
    	<div>
      	<h8><u>住所</u></h8><br>
      	<h6><b><%= @bar.address %></b></h6>
    	</div>
		  <div class="bar-show-category">
	      <h8><u>ジャンル</u></h8><br>
		    <h6><b><%= @bar.category %></b></h6>
		  </div>
		  <div class="bar-show-body">
		    <h8><u>紹介文</u></h8><br>
		    <h6><b><%= @bar.body %></b></h6>
		  </div>
    </div>

    <div class="col s6 offset-s1">
      <% if @posts.any? %>
      	<% @posts.each do |post| %>
          <div class="col s12 bar-show-box-all">
            <div class="col s5 bar-show-user">
              <u>投稿者</u>：
              <%= link_to(user_path(post.user)) do %>
              	<span><%= post.user.name %></span>
              <% end %>
              <div class="bar-show-post-image">
              	<%= attachment_image_tag post, :image, :fill, 130, 130, format: 'jpg', fallback: "bar_no_image.png" %>
            	</div>
            </div>
            <div class="col s7 bar-show-post-date">
            	<div class=" col s12 bar-show-post-destroy">
              	<%= link_to "削除", admin_post_path(post), method: :delete, "data-confirm" => "本当に消しますか？",class:"col s4 offset-s1 waves-effect waves-light btn-small #b71c1c red darken-4" %>
              </div>
              <u>投稿日時</u>：<%= post.created_at.strftime("%m月%d日 %H時%M分") %>
              <div class="bar-show-post-title">
                <u>件名</u>：<%= post.title %>
              </div>
              <div class="bar-show-post-title">
                <u>内容</u>：<%= post.body %>
              </div>
            </div>
          </div>
        	<div class="col s11 bar-show-box-comment">
          	<div class="bar-show-comment-index">＜<u>コメント一覧</u>＞</div>
          </div>
          <div id="post-<%= post.id %>-comment_area">
          	<%= render  partial: 'comments/index', locals: { comments: post.comments } %>
          </div>
          <div class="blank"></div>
          <div class="col s8 bar-show-box-comment">
            <% if user_signed_in? %>
            	<%= render  partial:'comments/form', locals: { comment: @comment, bar: @bar, post: post  } %>
            <% end %>
      		</div>
        <% end %>
      <% else %>
        <div class="col s12 bar-show-box-comment-none">
          <div><b>まだ投稿はありません</b></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col s2 offset-s8 page-change">
    	<%= paginate @posts, class: "paginate ,#546e7a blue-grey darken-1" %>
    </div>
  </div>
  <div class="post-index-blank" ></div>
</div>